---
- name: Add td-agent GPG key.
  rpm_key:
    key: https://packages.treasuredata.com/GPG-KEY-td-agent
    state: present

- name: Set Amazon link structure (v3).
  set_fact: amz_release_ver = "$releasever/$releasever"
  when: fluentd_version == 3

- name: Set Amazon link structure (v4).
  set_fact: amz_release_ver = "$releasever"
  when: fluentd_version != 3

- name: Debug
  debug:
    msg: "{{ ansible_facts['amz_release_ver'] }}"

- name: Add td-agent repository.
  template:
    src: td.amz.repo.j2
    dest: /etc/yum.repos.d/td.repo
    mode: 0644
